// _patch_corpus.js — 问答引擎接入全量语料 CORPUS_CHUNKS（29,389 段）
const fs = require('fs');
const P = 'index.html';
let s = fs.readFileSync(P, 'utf-8');

const NEW = [
'/* 全量语料懒加载：首次提问时才载入 2.21MB（29,389 段），之后常驻内存 */',
'var _cc=null,_ccLoading=false,_ccCbs=[];',
'function loadCorpus(cb){',
'  if(_cc){ cb(_cc); return; }',
'  _ccCbs.push(cb);',
'  if(_ccLoading) return;',
'  _ccLoading=true;',
'  var sc=document.createElement("script");',
'  sc.src="data/corpus_chunks.js";',
'  sc.onload=function(){',
'    _cc=(typeof CORPUS_CHUNKS!=="undefined")?CORPUS_CHUNKS:null;',
'    var cbs=_ccCbs; _ccCbs=[]; cbs.forEach(function(f){ f(_cc); });',
'  };',
'  sc.onerror=function(){ var cbs=_ccCbs; _ccCbs=[]; cbs.forEach(function(f){ f(null); }); };',
'  document.head.appendChild(sc);',
'}',
'function searchCorpus(g,topN){',
'  if(!_cc||!_cc.d) return [];',
'  var out=[],V=_cc.v,D=_cc.d;',
'  for(var i=0;i<D.length;i++){',
'    var d=D[i],t=d[2],sc=0,hit=0;',
'    for(var j=0;j<g.length;j++){ if(g[j].length>=2 && t.indexOf(g[j])>=0){ sc+=3; hit++; } }',
'    if(hit>0) out.push({bv:V[d[0]],sec:d[1],text:t,s:sc+hit*hit,hit:hit});',
'  }',
'  out.sort(function(a,b){ return b.s-a.s; });',
'  return out.slice(0,topN||5);',
'}',
'function qaAsk(){',
'  var el=$("qaAskInput"),q=(el&&el.value||"").trim(),box=$("qaAskResult");',
'  if(!box) return;',
'  if(!q){ box.innerHTML="<div class=\\"qa-ans-empty\\">先写个问题</div>"; return; }',
'  box.innerHTML="<div class=\\"qa-ans-empty\\">正在检索 29,389 段语料…</div>";',
'  var g=qaAskTokens(q), cards=qaAskSearch(q,3);',
'  loadCorpus(function(cc){',
'    var evs=cc?searchCorpus(g,5):[];',
'    if(!cards.length && !evs.length){',
'      box.innerHTML="<div class=\\"qa-ans\\"><div class=\\"qa-ans-empty\\">语料里没找到相关的，换个说法试试（试试「内耗」「男阳」「边界」）</div></div>";',
'      return;',
'    }',
'    var h="<div class=\\"qa-ans\\">";',
'    h+="<div class=\\"qa-ans-top\\"><span class=\\"qa-ans-q\\">"+esc(q)+"</span><span class=\\"qa-ans-score\\">语料 "+evs.length+" 段 · 卡片 "+cards.length+" 张</span></div>";',
'    var c=cards.length?cards[0].c:null;',
'    var body=(c&&c.answerBrief)||(c&&c.insight&&c.insight[0])||(evs[0]&&evs[0].text)||"";',
'    if(body) h+="<div class=\\"qa-ans-body\\">"+esc(body)+"</div>";',
'    if(evs.length){',
'      h+="<div class=\\"qa-ans-sub\\">老师原话 · 全量语料</div>";',
'      evs.forEach(function(e,i){',
'        var mm=Math.floor(e.sec/60)+":"+String(e.sec%60).padStart(2,"0");',
'        h+="<div class=\\"qa-ans-ev\\">"+String(i+1)+". "+esc(e.text)+"<div class=\\"qa-ans-ev-meta\\">"',
'          +"<a class=\\"ev-go\\" href=\\"javascript:void(0)\\" onclick=\\"event.stopPropagation();qaAskPlay(this,\\\\""+e.bv+"\\\\","+e.sec+")\\" title=\\"网页内嵌播放\\">▶ "+mm+"</a>"',
'          +"<a class=\\"ev-ext\\" href=\\"https://www.bilibili.com/video/"+e.bv+"/?t="+e.sec+"\\" target=\\"_blank\\" rel=\\"noopener\\">B站 ↗</a>"',
'          +"</div></div>";',
'      });',
'    }',
'    if(c&&c.quote) h+="<div class=\\"qa-ans-sub\\">金句</div><div class=\\"qa-ans-body\\" style=\\"background:var(--yin-soft);border-left-color:var(--yin)\\">"+esc(c.quote)+"</div>";',
'    if(cards.length){',
'      h+="<div class=\\"qa-ans-sub\\">相关卡片</div><div class=\\"qa-ans-rel\\">";',
'      cards.forEach(function(x){',
'        h+="<div class=\\"qa-ans-rel-item\\" onclick=\\"qaNavCardDirect(\\\\""+esc(x.c.qaId)+"\\\\")\\">▸ "+esc(x.c.question||"")+"</div>";',
'      });',
'      h+="</div>";',
'    }',
'    h+="</div>";',
'    box.innerHTML=h;',
'  });',
'}'
].join('\n');

// 替换原 qaAsk 函数（从 "function qaAsk(){" 到下一个行首 "}"）
const re = /function qaAsk\(\)\{[\s\S]*?\n\}\n/;
if (!re.test(s)) { console.error('qaAsk not found'); process.exit(1); }
s = s.replace(re, NEW + '\n', 1);
fs.writeFileSync(P, s, 'utf-8');
console.log('已接入全量语料，文件大小', s.length);
